### ISSUE TITLE
Furhter abstraction of the Eventbus-DSL.

### ISSUE THREAD

**Issue by ChachyDev** [ChachyDev/kotlin-forge-api#1]
Currently, the Eventbus-DSL heavily relies on the Forge EventBus. Due to some mods using alternative event buses, for example, a popular choice is https://github.com/KevinPriv/KEventBus it would be easier to abstract the current DSL even further.

We could create an interface that the Forge EventBus and custom event buses can implement to call to register code.

Example:
```kotlin
interface EventBus {
  fun <T> register(event: Class<T>, action: T.() -> Unit) 
}
```

**Comment by isXander** [comment]
How would the forge event bus implement this interface?

**Comment by ChachyDev** [comment]
In development, I ran into a few issues so I have reworked it. Once I test my code I will push it to a branch and you can explore how it would work after
